# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    identifier: research
    weight: 10
  - name: BO & Data-Driven Optimization
    parent: research
    url: "research/#bo-ddo"
    weight: 1
  - name: RL & Process Control
    parent: research
    url: "research/#rl-control"
    weight: 2
  - name: LLMs & AI Agents
    parent: research
    url: "research/#llms"
    weight: 3
  - name: Discovery & Molecular Design
    parent: research
    url: "research/#discovery"
    weight: 4
  - name: Sustainability & Supply Chains
    parent: research
    url: "research/#sustainability"
    weight: 5
  - name: All Publications
    parent: research
    url: "research/#all-publications"
    weight: 6
  - name: News
    url: news
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 50
  - name: Learning Resources
    url: learning-resources
    weight: 60
  - name: Contact
    url: contact
    weight: 70
